/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AudioPost = IDL.Record({
  'id' : IDL.Text,
  'listens' : IDL.Nat,
  'title' : IDL.Text,
  'audio' : ExternalBlob,
  'description' : IDL.Text,
  'audioPath' : IDL.Text,
  'author' : IDL.Principal,
  'replyTo' : IDL.Opt(IDL.Text),
  'kidFriendly' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserStatistics = IDL.Record({
  'totalListens' : IDL.Nat,
  'totalUploads' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAudioPost' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'addToFavorites' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editAudioPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAudioBlob' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getAudioPost' : IDL.Func([IDL.Text], [IDL.Opt(AudioPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoritePosts' : IDL.Func([], [IDL.Vec(AudioPost)], []),
  'getKidFriendlyPosts' : IDL.Func([], [IDL.Vec(AudioPost)], ['query']),
  'getMyContent' : IDL.Func([], [IDL.Vec(AudioPost)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatistics' : IDL.Func([], [UserStatistics], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listenToAudioPost' : IDL.Func([IDL.Text], [], []),
  'removeAudioPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AudioPost = IDL.Record({
    'id' : IDL.Text,
    'listens' : IDL.Nat,
    'title' : IDL.Text,
    'audio' : ExternalBlob,
    'description' : IDL.Text,
    'audioPath' : IDL.Text,
    'author' : IDL.Principal,
    'replyTo' : IDL.Opt(IDL.Text),
    'kidFriendly' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserStatistics = IDL.Record({
    'totalListens' : IDL.Nat,
    'totalUploads' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAudioPost' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'addToFavorites' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editAudioPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAudioBlob' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getAudioPost' : IDL.Func([IDL.Text], [IDL.Opt(AudioPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoritePosts' : IDL.Func([], [IDL.Vec(AudioPost)], []),
    'getKidFriendlyPosts' : IDL.Func([], [IDL.Vec(AudioPost)], ['query']),
    'getMyContent' : IDL.Func([], [IDL.Vec(AudioPost)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatistics' : IDL.Func([], [UserStatistics], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listenToAudioPost' : IDL.Func([IDL.Text], [], []),
    'removeAudioPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };